---
namespace: stevefulme1
name: argocd
version: 0.2.0
readme: README.md
authors:
  - Red Hat (@redhat)
description: Ansible collection for managing Argo CD and Argo Workflows
license:
  - GPL-3.0-only
license_file: LICENSE
tags:
  - argocd
  - argo
  - cloud
  - workflows
  - gitops
  - kubernetes
  - continuous_delivery
dependencies: {}
repository: https://github.com/stevefulme1/redhat.argocd
documentation: https://github.com/stevefulme1/redhat.argocd
homepage: https://github.com/stevefulme1/redhat.argocd
issues: https://github.com/stevefulme1/redhat.argocd/issues
build_ignore:
  - .gitignore
  - .ansible-lint
  - .yamllint
  - .github
  - changelogs/.plugin-cache.yaml
  - tests/output
  - "*.tar.gz"
  - "*.pyc"
  - __pycache__
  - .pytest_cache
  - .vscode
  - .idea
